apiVersion: batch/v1
kind: Job
metadata:
  name: bjack-job
spec:
  template:
    spec:
      containers:
      - name: bjack-job
        image: yash5090/bjack:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
